### ISSUE TITLE
Proxy / Browser

### ISSUE THREAD

**Issue by Futureganteng** [promptdrake/spotify-creator#1]
Ini bukan issue sih, cuma bisa connect proxy atau tidak?, sama apakah bisa run di ubuntu server (tanpa gui)

**Comment by promptdrake** [comment]
> Ini bukan issue sih, cuma bisa connect proxy atau tidak?, sama apakah bisa run di ubuntu server (tanpa gui)

Proxy gbisa dikarenakan belom punya bahan buat ujicoba
Try pake vpn
